name: workout_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_icon_button: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pie_chart: ^5.3.2
  rename: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/workout_app_icon.png'

flutter_native_splash:
  color: "#1b2447"
  image: assets/workout_app_icon.png

flutter:
  uses-material-design: true
  assets:
    - lib/icons/weight.png
    - lib/icons/done.png
    - lib/icons/not_done.png
    - lib/icons/in_progress.png
    